const number1 = 2;
const number2 = 4;
const product = number1 * number2;
console.log(product);
console.log(typeof product);
const charge = 5;
const payment = 3;
const amountRemaining = charge - payment;
console.log(amountRemaining);
console.log(typeof amountRemaining);
const test = 90;
const assignments = 100;
const final = 80;
const grade = (test + assignments + final) / 3;
console.log(grade);
console.log(typeof grade);
const firstName = 'Sarah ';
const lastName = 'You';
const fullName = firstName + lastName;
console.log(fullName);
console.log(typeof fullName);
const pH = 5;
const isAcidic = pH < 7;
console.log(isAcidic);
console.log(typeof isAcidic);
const numberOfSoldiers = 150;
const isSparta = (numberOfSoldiers === 300);
console.log(isSparta);
console.log(typeof isSparta);
let nickname = fullName;
nickname = fullName + ' is the GOAT';
console.log(nickname);
console.log(typeof nickname);
